name: document_measure
description: This package lets you measure distances in documents. The main use will probabily be technical documents and floorplans, but you are welcome to experiment with it.
version: 0.0.1+2
repository: "https://github.com/arconsis/measurements"
issue_tracker: "https://github.com/arconsis/measurements/issues"

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ^1.12.0

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  path_provider: ^2.1.1
  rxdart: ^0.27.7

dev_dependencies:
  bloc_test: ^9.1.5
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  pedantic: ^1.11.1

flutter:
  assets:
    - assets/
    - assets/images/
    - assets/images/pin_point.png
    - assets/images/example_portrait.png
    - assets/images/example_landscape.png

  plugin:
    platforms:
      android:
        package: com.arconsis.documentmeasure
        pluginClass: DocumentMeasurePlugin
      ios:
        pluginClass: DocumentMeasurePlugin

